spring:
  application:
    name: driver-service
  cloud:
    zookeeper:
      connect-string: bdtnode08:2181,bdtnode09:2181,bdtnode10:2181

#  dubbo.application.name=xsql-executor-provider
#  dubbo.registry.address=zookeeper://bdtnode10:2181
#  dubbo.registry.simplifed=true
#  dubbo.protocol.name=dubbo
#  dubbo.protocol.port=20880
#  dubbo.provider.token=true


dubbo:
  consumer:
    timeout: 1000
  application:
    name: driver-dubbo-provider
  registry:
    address: zookeeper://bdtnode10:2181
    simplifed: true
  protocol:
    name: dubbo
    port: 20881
    serialization: fst
#    optimizer: com.ane56.xsql.service.serial.SerializationOptimizerImpl
  provider:
    token: true

server:
  port: 10086