spring:
  application:
    name: driver-service
  cloud:
    nacos:
      username: nacos
      password: nacos
      server-addr: bdtnode10:8848
      discovery:
        server-addr: bdtnode10:8848
        enabled: true

dubbo:
  consumer:
    timeout: 1000
  application:
    name: driver-dubbo-provider
  registry:
    address: nacos://bdtnode10:8848?username=nacos&password=nacos
    simplifed: true
  protocol:
    name: dubbo
    port: 20881
    serialization: fst
#    optimizer: com.ane56.xsql.service.serial.SerializationOptimizerImpl
  provider:
    token: true

server:
  port: 10086