spring:
  application:
    name: executor-service
  cloud:
    nacos:
      username: nacos
      password: nacos
      server-addr: bdtnode10:8848
      discovery:
        server-addr: bdtnode10:8848
        enabled: true


dubbo:
  application:
    name: executor-dubbo-provider
  registry:
    address: nacos://bdtnode10:8848?username=nacos&password=nacos
  protocol:
    name: dubbo
    port: 20880
    serialization: fst
#    optimizer: com.ane56.xsql.service.serial.SerializationOptimizerImpl
  provider:
    token: true

server:
  port: 10087