spring:
  application:
    name: executor-service
  cloud:
    zookeeper:
      connect-string: bdtnode08:2181,bdtnode09:2181,bdtnode10:2181
    nacos:
      username: nacos
      password: nacos
      server-addr: bdtnode10:8848/nacos

#  dubbo.application.name=xsql-executor-provider
#  dubbo.registry.address=zookeeper://bdtnode10:2181
#  dubbo.registry.simplifed=true
#  dubbo.protocol.name=dubbo
#  dubbo.protocol.port=20880
#  dubbo.provider.token=true

dubbo:
  application:
    name: executor-dubbo-provider
  registry:
#    address: zookeeper://bdtnode10:2181
    address: nacos://bdtnode10
    port: 8848
    simplifed: true
  protocol:
    name: dubbo
    port: 20880
    serialization: fst
#    optimizer: com.ane56.xsql.service.serial.SerializationOptimizerImpl
  provider:
    token: true

server:
  port: 10087