server:
  port: 6666

spring:
  cloud:
    gateway:
      discovery:
        locator:
          lowerCaseServiceId: true
          enabled: true
      routes:
        - id: driver_route
          uri: http://localhost:9998
          order: 1
          predicates:
            - Path=/**
#          filters:
#            - StripPrefix=1