server:
  port: 6666
spring:
  application:
    name: xsql-gateway
  cloud:
    gateway:
      routes: # 路由数组, [路由, 就是指定当请求满足什么条件的时候转到哪个微服务]
        - id: xsql-driver_route # 当前路由的标识, 要求唯一
        uri: http://localhost:9998 # 请求要转发到的地址
        order: 1 # 路由的优先级, 数字越小, 级别越高
        predicates: # 断言(就是路由转发要满足的条件)
          - Path=/xsql-driver/**
          - StripPrefix=1 # 转发之前去掉一层路径
